# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: ThreatPatrols.com
site_url: https://documentation.threatpatrols.com/
site_author: Threat Patrols Pty. Ltd.
site_description: Persistent cybersecurity threat management

# Repository
repo_name: threatpatrols/documentation
repo_url: https://github.com/threatpatrols/documentation

# copyright
copyright: Copyright &copy; 2021 - 2024 Threat Patrols Pty. Ltd.

nav:
  - Documentation: index.md
  - OPNsense Resources:
    - opnsense/index.md
    - OPNsense Repo: opnsense/repo/index.md
    - OPNsense Mirror: opnsense/mirror/index.md
    - Autossh Plugin: opnsense/plugins/autossh/index.md
    - ConfigSync Plugin: opnsense/plugins/configsync/index.md
  - ThreatPatrols.com: https://www.threatpatrols.com

# theme configuration
theme:
  name: material
  language: en
  search_index_only: true
  include_search_page: false

  features:
    - content.code.annotate
    # - content.tabs.link       # When enabled, all content tabs across the whole documentation site will be linked and switch to the same label when the user clicks on a tab
    - content.tooltips
    # - header.autohide         # When autohiding is enabled, the header is automatically hidden when the user scrolls past a certain threshold, leaving more space for content
    - navigation.expand         # When expansion is enabled, the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually
    - navigation.indexes        # When section index pages are enabled, documents can be directly attached to sections, which is particularly useful for providing overview pages.
    - navigation.instant        # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page.
    #- navigation.prune         # Experimental feature
    - navigation.sections       # When sections are enabled, top-level sections are rendered as groups in the sidebar for viewports above 1220px, but remain as-is on mobile.
    - navigation.tabs           # When tabs are enabled, top-level sections are rendered in a menu layer below the header for viewports above 1220px, but remain as-is on mobile.
    - navigation.tabs.sticky    # When sticky tabs are enabled, navigation tabs will lock below the header and always remain visible when scrolling down.
    - navigation.top            # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again. It's rendered centered and just below the header.
    - navigation.tracking       # When anchor tracking is enabled, the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    #- toc.follow               # Experimental feature
    - toc.integrate             # When navigation integration for the table of contents is enabled, it is always rendered as part of the navigation sidebar on the left.
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/threatpatrols-eyeprint-white-64x64.png
  favicon: assets/threatpatrols-eyeprint-black-64x64.png

# plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        opnsense/plugins/index.md: opnsense/index.md
        opnsense/multicloudsense/index.md: opnsense/index.md
  - minify:
      minify_js: true
      minify_css: true
      minify_html: true

# extra
extra:

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

  social:
    - icon: octicons/browser-16
      link: https://www.threatpatrols.com
    - icon: fontawesome/brands/github
      link: https://github.com/threatpatrols
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/threatpatrols

# extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
