# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: ThreatPatrols.com
site_url: https://docs.threatpatrols.com/
site_author: Threat Patrols Pty Ltd
site_description: Awesome this and that

# Repository
repo_name: threatpatrols/documentation
repo_url: https://github.com/threatpatrols/documentation

# copyright
copyright: Copyright &copy; 2021 - 2022 Threat Patrols Pty Ltd

nav:
  - Documentation: index.md
  - MultiCLOUDSense: multicloudsense/index.md
  - OPNsense Plugins: opnsense-plugins/index.md
  - ThreatPatrols.com: https://www.threatpatrols.com

# theme configuration
theme:
  name: material
  language: en
  search_index_only: true
  include_search_page: false

  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/favicon.png
  favicon: assets/favicon.png

# plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        changelog/foobar.md: other/foobar.md
  - minify:
      minify_js: true
      minify_css: true
      minify_html: true

# extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: octicons/browser-16
      link: https://www.threatpatrols.com
    - icon: fontawesome/brands/github
      link: https://github.com/threatpatrols
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/threatpatrols

# extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
